* 怎么认识自己
** 尽量客观、全面地阐述清楚认清自己地六大角度

   - 你的三观
   - 你的行为倾向N
   - 你的梦想（欲望）
   - 你的先天条件
   - 你的能力边界
   - 你的所处环境

   关于世界观，推荐阅读《世界观：现代人必须要懂地科学哲学和科学史》

*** 认清自己的三观

    最近这段时间特别巧，正好碰到两位同学同时换工作，而且都不太顺心。两人都是先裸辞再找工作地，花了一个月投了300多份简历却连面试邀请都没接到几个，有限的几个面试也很糟心，所以很是受挫。
    但两人面对挫折的反应却截然不同。一位说：“今年的运城不太好， 找个时间去寺庙里拜一下”；另一个却说“这次换工作太大意了，不应该先辞职再找工作的，一旦不顺心心态就急了，下次还是要先找好作再离职”。
    他们两人的反应就体现了不同的世界观是如何影响我们的态度和行为的。

#+begin_quote
第一位的世界观是相信世上有佛，而且佛在控制者人的运程，于是碰到问题她会想着去拜佛以改运；
第二位的世界观则没有体现出对佛或其它超自然存在的信仰，因此碰到问题她会更多去找具体的原因。
#+end_quote

世界观与人生观、价值观一起被称为三观，它们决定着我们看待世界、看待人生以及看待事物价值的根本态度。

1. 世界观：世界观是一个人对世界总的看法和根本观点，它影响着你的人生观和价值观。
   比如，柏拉图的哲学体系就是构建在地球是宇宙中心这个世界观基础上的。
   再比如，一个相信世界是由上帝创造的人，跟一个纯粹的唯物主义者相比，两者眼中的世界是大不相同的，因此他们的人生观、价值观也会有很大的差异。
2. 人生观：人生观是一个人对人生的看法，也就是对于人类生存的目的、价值和意义的看法。
   比如，有人的世界观是“人生在世，吃喝二字”，也就是要过得轻松快乐。有人的人生观则是“为下辈子或下几辈子修炼”或“要青史留名”。
   *这些人生观就是世界观在看待人生上的体现*，比如“为下辈子或下几辈子修炼”的人生观就是“相信世间有佛”的世界观的体现。
3. 价值观：价值观是一个人对事物价值的总的看法和根本观点，他一方面表现为价值取向、价值追求；另一方面表现为判断事物有无价值及价值大小的评价尺度和准则。
   比如，有人视金钱为最高的价值追求，而有人则视金钱为身外之物甚至视为粪土。
   因此，要正确认清自己，你就要花点时间来捋一下自己的三观，这样你就会知道为何你会持有某种观念，为何你会认为有些人讲的好有道理，为何你认为胡说八道的人却有很多人追捧等等。

   想要进一步确立自己的世界观，推荐阅读《世界观：现代人必须要懂的科学哲学和科学史》

*** 认清自己的梦想（欲望）

    我儿子刚上幼儿园小班，我问他：你长大后的梦想是什么？他说想做一名厨师。
    我又问他：为什么你想做一名厨师呢？他回答：这样我就可以做很多好吃的给自己吃呀。
    梦想就是现在想未来的事，所以哪怕是很小的小孩子，心里也是有梦想的，虽然听起来很搞笑，但这却很好地体现了他当下的某个欲望。
    梦想的本质是一个人的三观在奋斗目标（欲望）上的集中表现,之所以要将梦想单独拿出来讲清一番，目的在于要确认下你的梦想是否跟你的三观一致。
    人是一种容易从众的社会性动物，很多时候我们自以为的梦想不过是一个跟风的目标而已。
    比如，在元朝和明朝绝大多数读书的梦想就是为了中科举做官。
    改革开放初期，在造导弹不如卖茶叶蛋的重商氛围下，很多人的梦想就是做生意赚钱。
    以这些年很热的创业梦想为例。如果你的创业梦想还是在“大众创新，万众创业”的浪潮下产生的话，你就需要好好捋一捋，你的创业梦只是跟风，还是你的的三观的体现呢？
    如果是前者的话，你就可以好好思考下，是否还有其它更符合你三观的梦想存在呢？

*** 认清自己的行为倾向

    春节的时候带小孩在景点玩，那人叫一个多。稍微热门一点的项目就是两排长长的人龙，排上一个小时都不一定能轮上，几乎人人都排的心焦气躁的。
    我记得在排队等缆车的时候，几乎要排到我们的时候，有位妈妈拉着小孩就插队到我们前面了，边插队还边说“我们之前就排队了，刚刚是带小孩去洗手间了”。
    我下意识的反应就是退后避让。结果排在我后面的一个面色潮红的姑娘不干了，尖着嗓子就喊了“怎么这么没素质，不排队呢！”
    *在长时间排队耐心几乎耗尽的情况下，这是人的行为几乎就是本能的行为倾向了*。
    我的行为倾向是避让，而后面姑娘的行为是攻击。
    我们很多行为都是下意识的，比如，有人坐着晃腿，有人爱清净独处，有人爱发语音不爱写文字。
    这类行为倾向是很难控制的，因为你还没意识到它就已经发生了。
    因此你要先用各种评测，立体地了解下自己的行为倾向，这样你才有可能在某些情景下对这类行为提前做干预。
    
    为何一定要了解自己的行为倾向呢？原因有三个：
    
    1. 你可以清楚你在不受控制的状态下，最有可能形成怎样的态度，以及产生怎样的行为。
    2. 有条件的情况下，你可以尽量选择更适合你行为倾向的工作或社会角色，这样你花费更少的精力却可以做得更好。
    3. 你会更愿意调节自己在具体情景下的行为，因为你已经知道自己的某些行为属于下意识的行为倾向，这样调节起来你的心理障碍会更小。
       
行为倾向可通过一些性格或人格评测工具来了解，目前市面上流行的评测工具主要有MBTI、DISC、HBDI等等，这些评测都不够严谨科学，有较大的概率偏差，但对了解自我的行为倾向还是有一定帮助的。

*** 认清自己的先天条件

    篮球是一项看身高的运动，像CBA球员（中国职业篮球联盟）的平均身高是2.01米，NBA（美国职业篮球联盟）球员e平均身高也接近2米。
    在这么一个长人林立的圈子里，身高不足一米七的人参与进来会怎么样呢？
    像NBA，历史上身高不足一米七的只有九个人（还都是上世纪九十年代之前的，2000年之后的一位都没有），其中最出类拔萃的斯波特韦伯（1米68）职业生涯均就9.9份2.1篮板和5.3助攻，更其他身高正常的NBA球星动辄场均20多分相比，还是失色不少的。
    这就是先天条件的影响：如果你的先天条件不适合某个领域，你再励志，再出类拔萃也无法成为这个领域的顶尖人才。
    因此，在了解了你的态度和意识层面的三观、梦想、行为倾向后，你还要认清你客观的先天条件，在可能的条件下选择更适合你的先天条件的领域发展。
    这些先天条件主要包括你的性别、身高、相貌、肤色等等。

*** 认清自己的能力边界
    
    如果我请你徒手举起一个150斤中的麻包，只要举起来的话，我就给你一万块钱，你是不是可能会来挑战下？但如果我请你举起一个五百斤重的麻包，你还会接受这个挑战吗？
    我相信，哪怕我给你五百万你也不会接受。这两个挑战到底有什么不同呢？
    区别就在于前一个150斤的挑战还在你的能力或者能力成长边界内，你努力努力还是有可能做到的；但后一个500斤的挑战已经完全超出你的能力成长边界了，你在努力也是不可能做到的。
    在这个举例里，举重能力的能力边界因为相对比较清楚（普通人大概能举起自己体重60%～100%的重量，经过锻炼的人则可以举起比自己体重重115%～200%的重量），因此你会放弃对500斤举重的挑战。
    但在现实中，不少事情都是对很多种能力的综合要求，因此很多人就难以知道这件事是否已经远远超过了自己的能力成长边界。
    还以创业为例。
    创业是一个对人的综合能力要求很高的事，特别是中国经济从粗放式增长的时期进入到精细化增长的时期后，除了关系国计民生的部分领域外，大多数领域都已经进入了充分市场化竞争阶段，这种阶段下的创业要求远远高于之前改革开放初期靠资源、靠胆量、靠政策的创业要求。
    但大多数在选择创业时，只看到了创业可能带来的好处，却未评估创业是否超过了自己的能力成长边界。
    因此，我们还需要认清自己的能力以及能力成长边界，这样才不会作出挑战500斤举重的事。
    如何认清自己的能力及能力成长边界呢？
    一个很好的方法就是构建成是自己的能力树和知识体系。

*** 认清自己的所处环境

    三观、梦想、行为倾向、先天条件以及能力边界，这五项都是针对自己，往内看的。
    要认清自己，除了往内看，还要往外看，这就是认清自己所处的环境。
    举个例子
#+begin_quote
在中国以世袭制为主的两晋时期，一个平民家庭的孩子，有没有可能通过学富五车称为三公九卿呢？
就历史记载来看，绝无可能
首先，平民家庭的孩子要做到学富五车就很艰难了，但即使有人突破了这一点，在官员世袭的制度下，想改变先天出身成为三公九卿，那也是难如登天的一件事。
这就是环境对人的限制。
#+end_quote

自然环境会限制你的体验和活动范围；时代环境会限制你的视野和影响；你的诚征环境会影响你的三观和行为倾向；你所处的阶层环境会限制你的成长高度。
人最大的无力感，根源就来于超出环境上限的期待。
所以，认清自己所处的环境后，认命，不做超出环境上限的期待，这样本身不会去执念于你得不到的东西，从而也就不会那么焦虑了。

最后，人之所以会焦虑，核心的一点就在于发现自己对未来得 消极变化无能无力。
这种无能无力源于三点
#+begin_quote
梦想（欲望）与自己的三观不符，也就是追逐的目标对自己而言是消极的
梦想（欲望）超出了自身的先天条件、能力边界以及所处环境限制
自己不知道自己该做什么、能做什么以及可以怎么做
#+end_quote

通过认清自己的三观、梦想（欲望）、行为倾向、先天条件、能力边界以及所处的环境，你就更能够找到自己应该追逐的梦想，确定自己欲望的程度，以及清楚自己适合怎么去做。
